server:
  port: 9000

spring:
  application:
    name: backend-auth
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:auth
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9092