server:
  port: 8088

spring:
  application:
    name: backend-gateway-client
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: backend-auth-provider
            client-id: gateway-client-id
            client-secret: password123
            authorization-grant-type: authorization_code
            redirect-uri: "http://backend-gateway-client:8088/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          backend-auth-provider:
            issuer-uri: http://backend-auth:9000