server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG


spring:
  application:
    name: trade-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://backend-auth:9000

jwt-uri: http://backend-auth:9000/oauth2/jwks

offer-expiration-minutes: 5

starting-balance: 10000

