spring:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: user
    test:
      topic: user-created

starting-balance: 10000