coin-api-key: ${API_KEY}
coin-api-url: https://rest.coinapi.io/v1/exchangerate/

base-currency: USD
crypto-currencies: BTC,ETH

server:
  port: 8081
  
spring:
  application:
    name: exchange
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rate-mongo
  kafka:
    bootstrap-servers: localhost:9092